--- #YAML:1.0
name:               App-Templer
version:            0.9.1
abstract:           Extensible Static Site Generator.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:       ~
    HTML::Template:     ~
    Module::Pluggable:  ~
    Test::More:         ~
resources:
    bugtracker:  https://github.com/skx/templer/issues
    homepage:    https://github.com/skx/templer/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/templer.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
